### ISSUE TITLE
제보

### ISSUE THREAD

**Issue by qlzl123** [incheon-kim/ddcleaner#1]
현재 글/덧글 삭제시에 삭제 중이라는 퍼센트게이지가 올라가지만 1개만 삭제되고 나머진 삭제가 안되요
임시/삭제대기 게시판은 아닙니다!

**Comment by incheon-kim** [comment]
네 안그래도 저도 직접 사용중에 문제를 파악해서요.. 후딱 고치겠습니당..

**Comment by incheon-kim** [comment]
새로 빌드해서 배포했습니다 :)
[여기](https://github.com/incheon-kim/ddcleaner/releases/latest)
