### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by zakmyo** [incheon-kim/ddcleaner#16]
![image](https://user-images.githubusercontent.com/45200809/155884289-3b897b62-d1b9-4e8f-a70d-ed3927b80c57.png)

동작안함 그냥 로그인 되고 댓글목록 보여주고 끝남

**Comment by incheon-kim** [comment]
[1.3.1]([https://github.com/incheon-kim/ddcleaner/releases/latest) 에서 해결되었습니다.

**Comment by incheon-kim** [comment]
Windows용 바이너리는 곧 업로드될 예정입니다.
