### ISSUE TITLE
댓글 목록 수집중에서 무한로딩입니다.

### ISSUE THREAD

**Issue by s00ny** [incheon-kim/ddcleaner#4]
<img width="293" alt="20210112_004718" src="https://user-images.githubusercontent.com/77287652/104203753-da917180-546f-11eb-9fa5-0a29c94c1750.png">

페이지를 하나로 지정해놓아도 계속 무한 로딩중이네요 ㅜㅜ

**Comment by incheon-kim** [comment]
다른 일과 생활에 전념중이라 천천히 확인해보겠습니다 ㅜ.ㅜ

**Comment by devhojaelee** [comment]
댓글이 무한 로딩입니다. ㅠ.ㅠ 
고쳐주세요 ㅠ.ㅠ

**Comment by incheon-kim** [comment]
@s00ny @devhojaelee 
https://github.com/incheon-kim/ddcleaner/releases/latest

댓글 URL의 사소한 변화가 있었는데 Exception 처리를 안하다보니 문제가 생겼네요 :(
해당 사항 1.2.3 에서 수정했습니다 :)
